Make Prometheus rps graphs rate() time range configurable
tarantool/grafana-dashboard pull request #47
Opened 2021-01-21 07:06 UTC by DifferentialOrange

Closes #46 

Change example container Prometheus scrape time. Make Prometheus rps graphs rate() time range configurable on import.

![image](https://user-images.githubusercontent.com/20455996/105315216-0c24de00-5bd0-11eb-8451-df741274dfe0.png)

![Screenshot from 2021-01-21 10-04-48](https://user-images.githubusercontent.com/20455996/105315380-41313080-5bd0-11eb-8bb1-306f5db75939.png)

2021-01-22 07:13 UTC, vasiliy-t requested changes
I suggest to: 
- review and document possible alternatives
- outline pros/cons of each possible solution
to be sure that we have selected right solution

2021-01-22 14:27 UTC, DifferentialOrange commented
@vasiliy-t 

We need to set rate() vectors time range while being consistent with Prometheus scrape interval. There are some articles on how you should choose the variable: https://www.robustperception.io/what-range-should-i-use-with-rate , https://www.metricfire.com/blog/understanding-the-prometheus-rate-function/?GAID=231802381.1611061565 . One of them says "There is no silver bullet here: at the very minimum it [time range] should be two times the scrape interval.", while the other one says "The general rule for choosing the range is that it should be at least 4x the scrape interval". I tried to use range equal to two scrape intervals with our docker cluster and it as good, but local cluster is less prone to network errors than the real one. On the other hand, Prometheus documentation says "the [rate] calculation extrapolates to the ends of the time range, allowing for missed scrapes or imperfect alignment of scrape cycles with the range's time period".

I have inspected a dozen of Community dashboard. They use one of the following approaches:
- hard-coded time ranges ('1m', '2m', '5m');
- internal `$__interval` variable.
It is also worth to mention that many dashboards used different time ranges for different graphs. Why? Using greater time range makes a graph smoother, but it's just an assumption.

Do these approaches work good? I don't think so.
Hard-coded '1m' time range will fail if Prometheus scrape time is greater or equal to '1m', which is default.
What's about `$__interval` variable -- https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/ ? In nature it hasn't got anything to do with scrape times or rate ranges. It's just a variable characterizing current dashboard time range. For example, it equals to '1m' if I set "last 6 hours" on my test dashboard. So if i set rate(...[$__interval]), it will break up my rps graps. It will be equal to sufficient '2m' if I inspect "last 12 hours" on my dashboard. I think we shouldn't base on it while calculating queries.

When I inspected `$__interval`, I found this hidden gem: https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/ . It's an internal variable for computing rate time range. But it's available since Grafana 7.2 only.

So what we can use to solve our problem?

1. Change hard-coded constants from `1m` to `2m`. All graphs should work for people with scrape intervals less or equal to `1m` (default is `1m`), otherwise they will need to fix it manually on each graph. **Pros**: simple for code, do not introduce any complications for people using the dashboard in case everything works fine. **Cons**: inconvenient to fix, works fine only under assumptions.
2. [Introduced in this PR] Configure variable on export (with default value `2m`). Behave like a string constant after set. **Pros**: add flexibility to user experience, do not introduce any complications for dashboard work after import. **Cons**: may confuse user a bit (the step of configuration may be ignored cause default is already set), inconvenient to fix if user decided to increase his scrape range or missed configuration step in the export step.
3. Constant Grafana variable (custom) (with default value '2m'). **Pros**: add flexibility to user experience, may be changed in the runtime, do not confuse user on export. **Cons**: last time I tried to use Grafana constant variable it had worked really bad both with grafonnet and Grafana itself (including update of a value), it also make query more complicated for Grafana processing.
4. 2+3 -- configure default value of constant variable on export. Same as 3 in nature.
5. Use `__interval` Grafana variable. **Cons**: it doesn't work this way, I don't understand why anyone will use it.
6. Use `__rate_interval` Grafana variable. **Pros**: not confuse user on export and should solve all problems automatically. Best solution. **Cons**: introduced in Grafana 7.2.
7. Use some custom-made `__rate_interval`-like variable. Is it possible? Not sure but worth checking up.

2021-01-22 14:54 UTC, DifferentialOrange commented
TODO: consider using `irate` instead of `rate`.

2021-01-28 07:56 UTC, DifferentialOrange commented
Closed in favor of #48

2021-01-28 07:56 UTC, closed without merging